import 'package:bls/utils/post/post_state.dart';
import 'package:get/get.dart';

class PostController extends GetxController {
  List<Post> posts = [
    Post(
        id: 1,
        role: "teacher",
        type: PostType.pdf,
        organizationId: 1,
        courseId: 1,
        bookId: 1,
        chapterId: 1,
        title: "Html Tutorial",
        description: "Learn HTML With this tutorial",
        images: null,
        link: "assets/html_tutorial.pdf",
        likes: [],
        doubts: []),
    Post(
        id: 1,
        role: "teacher",
        type: PostType.youtube,
        organizationId: 1,
        courseId: 1,
        bookId: 1,
        chapterId: 1,
        title: "Html Tutorial",
        description: "Learn HTML With this tutorial",
        images: null,
        link: "https://www.youtube.com/watch?v=yJaz64e2GvE",
        likes: [],
        doubts: []),
    Post(
        id: 1,
        role: "teacher",
        type: PostType.youtube,
        organizationId: 1,
        courseId: 1,
        bookId: 1,
        chapterId: 1,
        title: "Html Tutorial",
        description: "Learn HTML With this tutorial",
        images: null,
        link: "https://www.youtube.com/watch?v=MSICFljRcb4",
        likes: [],
        doubts: []),
    Post(
        id: 1,
        role: "teacher",
        type: PostType.pdf,
        organizationId: 1,
        courseId: 1,
        bookId: 1,
        chapterId: 1,
        title: "Html Tutorial",
        description: "Learn HTML With this tutorial",
        images: null,
        link: "assets/html_tutorial.pdf",
        likes: [],
        doubts: []),
    Post(
        id: 1,
        role: "teacher",
        type: PostType.pdf,
        organizationId: 1,
        courseId: 1,
        bookId: 1,
        chapterId: 1,
        title: "Html Tutorial",
        description: "Learn HTML With this tutorial",
        images: null,
        link: "assets/html_tutorial.pdf",
        likes: [],
        doubts: []),
    Post(
        id: 1,
        role: "teacher",
        type: PostType.images,
        organizationId: 1,
        courseId: 1,
        bookId: 1,
        chapterId: 1,
        title: "Html Tutorial",
        description: "Learn HTML With this tutorial",
        images: [
          "https://images.unsplash.com/photo-1617471346061-5d329ab9c574?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29tcHV0ZXIlMjBwcm9ncmFtbWluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
          "https://images.unsplash.com/photo-1564865878688-9a244444042a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cHJvZ3JhbW1pbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60"
        ],
        link: "assets/html_tutorial.pdf",
        likes: [],
        doubts: []),
  ];
}
